config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'

  get '/auth/spotify', as: :spotify_login
  get '/auth/spotify/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  post '/do/search', to: 'search#index'

  namespace :playlists do
    get '/:id', to: 'playlist#show'
    post '/create', to: 'playlist#create'
  end

  namespace :api do
    namespace :v1 do
      get '/my/token', to: 'token#show'
    end
  end
end

app/models/album.rb
class Album
  attr_reader :id,
    :name,
    :artwork,
    :artists

  def initialize(album_data)
    @id = album_data[:id]
    @name = album_data[:name]
    @artwork = album_data[:images].first[:url] if album_data[:images].length > 0

    @artists = album_data[:artists].map { |artist| Artist.new(artist) }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist
  attr_reader :id, :name, :href

  def initialize(artist_data)
    @id = artist_data[:id]
    @name = artist_data[:name]
    @href = artist_data[:href]
  end
end

app/models/playlist.rb
class Playlist
  attr_reader :id, :uri, :name, :tracks_uri, :track_count, :owner

  def initialize(playlist_data, spotify)
    @id = playlist_data[:id]
    @uri = playlist_data[:uri]
    @name = playlist_data[:name].gsub(/[^\s!-~]/i,'').strip
    @tracks_uri = playlist_data[:tracks][:href]
    @track_count = playlist_data[:tracks][:total]
    @owner = SpotifyUser.new(playlist_data[:owner])

    @spotify = spotify
  end

  def tracks
    playlist_tracks = @spotify.make_request("users/#{@owner.id}/playlists/#{@id}")
    playlist_tracks[:tracks][:items].map do |track_data|
      Track.new(track_data)
    end
  end
end

app/models/playlist_collection.rb
class PlaylistCollection < Array
  def self.from_spotify(spotify)
    new(spotify)
  end

  private
  def initialize(spotify)
    playlists = spotify.make_request('me/playlists')
    unless playlists[:items].nil?
      playlists[:items].each do |playlist|
        self << Playlist.new(playlist, spotify)
      end
    end
  end
end

app/models/spotify.rb
require 'base64'

class Spotify
  API_URL = "https://api.spotify.com/v1/"
  B64_AUTH = Base64.strict_encode64("#{ENV['spotify_client_id']}:#{ENV['spotify_client_secret']}")


  def self.from_user(user)
    new(user)
  end

  def check_token
    now = DateTime.now
    @user.token_expires > now
  end

  def refresh_token(force=false)
    return if check_token && !force

    conn = Faraday::new('https://accounts.spotify.com/api/token')

    response = conn.post do |req|
      req.headers['Authorization'] = "Basic #{B64_AUTH}"

      req.body = {
        grant_type: 'refresh_token',
        refresh_token: @user.refresh_token
      }
    end

    data = JSON.parse(response.body, symbolize_names: true)
    @user.token = data[:access_token]
    @user.refresh_token = data[:refresh_token] unless data[:refresh_token].nil?
    @user.token_expires = DateTime.now + data[:expires_in].seconds if data[:expires_in]
    @user.save!
  end

  def make_post_request(endpoint, parameters={})
    refresh_token

    conn = Faraday::new(url: "#{API_URL}#{endpoint}")

    response = conn.post do |req|
      req.headers['Authorization'] = "Bearer #{@user.token}"
      req.headers['Content-Type'] = 'application/json'
      req.body = parameters.to_json
    end

    data = JSON.parse(response.body, symbolize_names: true)

    unless data[:error].nil?
      if data[:error][:status] == 401
        refresh_token(true)
        return make_post_request(endpoint, parameters)
      end
    end

    data
  end

  def make_request(endpoint, parameters={})
    refresh_token
    conn = Faraday::new(url: "#{API_URL}#{endpoint}?#{parameters.to_query}")

    response = conn.get do |req|
      req.headers['Authorization'] = "Bearer #{@user.token}"
    end

    data = JSON.parse(response.body, symbolize_names: true)
    unless data[:error].nil?
      if data[:error][:status] == 401
        refresh_token(true)
        return make_request(endpoint, parameters)
      end
    end

    data
  end

  private

  def initialize(user)
    @user = user
  end
end

app/models/spotify_user.rb
class SpotifyUser
  attr_reader :display_name,
    :uri,
    :href,
    :external_href,
    :type,
    :id

  def initialize(user_data)
    @display_name = user_data[:display_name]
    @uri = user_data[:uri]
    @href = user_data[:href]
    @external_href = user_data[:external_urls][:spotify]
    @id = user_data[:id]
    @type = user_data[:type]
  end
end

app/models/track.rb
class Track
  attr_reader :artists, :id, :name, :album, :uri
  def initialize(track_data)
    data = track_data[:track]
    
    @artists = data[:artists].map { |artist| Artist.new(artist) }
    @id = data[:id]
    @name = data[:name]
    @uri = data[:uri]
    @local = data[:is_local]
    @album = Album.new(data[:album])
  end

  def local?
    @local
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :uid
  validates_presence_of :token
  validates_presence_of :refresh_token
  validates_presence_of :token_expires

  attr_reader :playlists, :spotify

  after_initialize :load_spotify, if: :persisted?
  after_save :load_spotify, if: :persisted?

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user| 
      new_user.uid = auth_info.uid
      new_user.token = auth_info.credentials.token
      new_user.refresh_token = auth_info.credentials.refresh_token
      new_user.token_expires = Time.at(auth_info.credentials.expires_at).to_datetime
    end
  end

  def create_playlist(name)
    @spotify.make_post_request("users/#{uid}/playlists", {name: name})
  end

  private
  def load_spotify
    @spotify ||= Spotify::from_user(self)
    @playlists ||= PlaylistCollection::from_spotify(@spotify)
  end
end

app/controllers/api/v1/search_controller.rb
class Api::V1::SearchController < ApplicationController
  def index
  end
end

app/controllers/api/v1/token_controller.rb
class Api::V1::TokenController < ApplicationController
  def show
    result = {token: nil}
    result[:token] = current_user.token if current_user
    render json: result
  end
end

app/controllers/api/v1/tracks_controller.rb
class Api::V1::TracksController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/playlists/playlist_controller.rb
class Playlists::PlaylistController < ApplicationController
  def show
    @playlist = current_user.playlists.select do |playlist|
      playlist.id == params[:id]
    end.first

    return redirect_to root_path if @playlist.nil?

    @tracks = @playlist.tracks
  end


  def create
    current_user.create_playlist(params[:name])
    redirect_to root_path
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    search_hash =  {
      type: 'track',
      q: search_params['query'].strip
    }

    @tracks = current_user.spotify.make_request('search', search_hash)[:tracks][:items]

    @tracks = @tracks.map do |track|
      Track.new({track: track})
    end
  end

  private
  def search_params
    params.require(:search).permit(:query)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.from_omniauth(request.env['omniauth.auth'])
      session[:user_id] = user.id
    end

    redirect_to root_path
  end

  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.slim
doctype html
html
  head
    title Moodify
    = csrf_meta_tags
    = csp_meta_tag

    = render partial: 'partials/fontawesome'
    = stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css'
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/js/materialize.min.js'
    = javascript_include_tag 'https://sdk.scdn.co/spotify-player.js'
    = javascript_include_tag 'application'

body.grey.darken-3.text-white
  = render partial: 'partials/navbar'
  .row.app
    .col.m3.sidebar.grey.darken-2
      - unless current_user.nil?
        h5.white-text Playlists
        hr
        = render partial: 'partials/player'
    .col.m9
      == yield

  .row.seekbar.grey.darken-4.white-text
    .col.s12.container.h100
      .row.bar.h100
        .col.s2.text-center.toggleButton
          i.far.fa-play-circle#playToggle
        .col.s8.progress.white
          .determinate.green.lighten-1(style='width: 0%')
        .col.s2.text-left.time
          p#value

app/views/partials/_fontawesome.slim
= stylesheet_link_tag "https://pro.fontawesome.com/releases/v5.0.13/css/regular.css", integrity: "sha384-HLkkol/uuRVQDnHaAwidOxb1uCbd78FoGV/teF8vONYKRP9oPQcBZKFdi3LYDy/C", crossorigin: "anonymous"
= stylesheet_link_tag "https://pro.fontawesome.com/releases/v5.0.13/css/brands.css", integrity: "sha384-t3MQUMU0g3tY/0O/50ja6YVaEFYwPpOiPbrHk9p5DmYtkHJU2U1/ujNhYruOJwcj", crossorigin: "anonymous"
= stylesheet_link_tag "https://pro.fontawesome.com/releases/v5.0.13/css/fontawesome.css", integrity: "sha384-LDuQaX4rOgqi4rbWCyWj3XVBlgDzuxGy/E6vWN6U7c25/eSJIwyKhy9WgZCHQWXz", crossorigin: "anonymous"

app/views/partials/_navbar.slim
nav.grey.darken-4(role="navigation")
  .nav-wrapper.container
    .brand-logo
      - unless current_user
        a.btn(style='background: #1db954;', href=spotify_login_path)
          i.fab.fa-spotify
          | Login with Spotify
      - else
        = link_to "Hello, #{current_user.uid} ", root_path
        = link_to "Logout", logout_path, class: 'btn', style: 'background: #1db954'

    ul.right
      li
        = form_tag '/do/search', id: 'searchForm'
          div.input-field
            = text_field :search, :query, id: 'search'
          label.label-icon(for='search')
            i.far.fa-search

app/views/partials/_player.slim
= render partial: 'partials/user/playlists'

app/views/partials/_tracks.slim
table#tracks.white-text
  thead
    tr
      th Name
      th Artist
  tbody
    - @tracks.each do |track|
      tr(data-track-uri=track.uri)
        td= track.name
        td= track.artists.map(&:name).join(', ')

app/views/partials/user/_playlists.slim
ul#playlists
  li
    = form_tag playlists_create_path do
      = label_tag 'name'
      = text_field_tag 'name', nil, placeholder: 'New playlist name...'
      = submit_tag 'Create Playlist', class: 'btn'

  - current_user.playlists.each do |playlist|
    li
      = link_to playlist.name, "/playlists/#{playlist.id}"

app/views/playlists/playlist/show.slim
= render partial: 'partials/tracks', locals: {tracks: @tracks}

app/views/search/index.slim
= render partial: 'partials/tracks'